import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/pages/Home.module.css'
import Habilit_box from './components/habilit_box'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page1} ${inter.className}`} id="page1">
        <ul>
          <ul className={styles.hello}>
            Olá, eu sou
          </ul>
          Luiz Henrique Barros
          <li>
            Desenvolvedor Front-End<hr className={styles.pointer} />
          </li>
          <li className={styles.contact_me}>
            <button type="button">Me Contate</button>
          </li>
        </ul>
        <Image src="/image/" width="200" height="200" />
      </div>
      <div className={styles.page2} id="page2">
        <Image src="/images/" width="200" height="200" />
        <ul>
          <li className={styles.title}>
            Sobre mim
          </li>
          <li className={styles.text}>
          Sou uma pessoa determinada que estou sempre em constante estudo, sempre buscando aprender novas tecnologias e ferramentas do mercado e me envolver em projetos novos buscando sempre me arriscar em me expor a novos desafios. <br />
          Sou um profissional que adquiri tato as requisições e desejos do consumidor final pela experiência adquirida como programador Front-end, Delphi e suporte no ERP da minha última empresa.
          </li>
        </ul>
      </div>
      <div className={styles.page3} id="page3">
        <Habilit_box />
        <ul>
          <li className={styles.habilits}>
            Habilidades
          </li>
          <li className={styles.habilit_title} id="habilit_title">
            title
          </li>
          <li className={styles.habilit_description} id="habilit_description">
          </li>
        </ul>
      </div>
    </>
  )
}